export const starNames = [
  "Aldebaran",
  "Alpha Hydri",
  "Altair",
  "Beta Pictoris",
  "Canis Minoris",
  "Canum Venaticorum",
  "Comae Berenices",
  "Chi Herculis",
  "Cygni",
  "Delta Equulei",
  "Denebola",
  "Epsilon Serpentis",
  "Eta Scorpii",
  "Fomalhaut",
  "Gamma Tucanae",
  "Iota Virginis",
  "Kappe Doradus",
  "Lambda Arae",
  "Leonis Minoris",
  "Mu Cassiopeiae",
  "Nu Octantis",
  "Omicron Aquilae",
  "Ophiuchi",
  "Pi Mensae",
  "Pollux",
  "Procyon",
  "Psi Capricorni",
  "Rho Puppis",
  "Sigma Ursae",
  "Sirius",
  "Tau Cygni",
  "Theta Sculptoris",
  "Upsilon Aquarii",
  "Ursae Majoris",
  "Vega",
  "Xi Pegasi",
  "Zeta Leporis",
];
